### ISSUE TITLE
Reply Bug

### ISSUE THREAD

**Issue by IanMitchell** [IanMitchell/aquarius#264]
```
(node:80304) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'set' of undefined
    at records.forEach.reply (/Users/ianm/Code/aquarius/src/bot/commands/reply.js:43:37)
    at Array.forEach (<anonymous>)
    at aquarius.guilds.map (/Users/ianm/Code/aquarius/src/bot/commands/reply.js:42:15)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

**Comment by IanMitchell** [comment]
Fixed
